- name: Test Action
  hosts: all
  tasks:
    - name: Copy file
      copy:
        src: ../files/requirements.yml
        dest: /tmp/requirements.yml
    - name: Install cowsay
      become: yes
      apt:
        name: cowsay
        update_cache: yes
