name: Test Action

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: With sudo
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          sudo: true
          options: --inventory hosts
